DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS teams;


CREATE TABLE team (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
team_name VARCHAR(50) NOT NULL 
);

CREATE TABLE car (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    model VARCHAR(30) NOT NULL,
    engine VARCHAR(30) NOT NULL,
    team_id INTEGER,
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE SET NULL
    );

CREATE TABLE driver (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    team_id INTEGER,
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE SET NULL,
    driver_id INTEGER,
    FOREIGN KEY (driver_id) REFERENCES driver(id) ON DELETE SET NULL
    );


