DROP TABLE IF EXISTS driver;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS team;

CREATE TABLE driver (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    car VARCHAR(30) NOT NULL,
    team VARCHAR(30) NOT NULL 
    );

CREATE TABLE team (
id INT NOT NULL AUTO_INCREMENT,
team VARCHAR(30) NOT NULL 
PRIMARY KEY (id)
);

CREATE TABLE car (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    model VARCHAR(30) NOT NULL,
    engine VARCHAR(30) NOT NULL,
    team VARCHAR(30) NOT NULL 
    );